"""Bundle the theory files in the input folder into a JS file for the web build.

Usage: python3 web/bundle_inputs.py <input-dir> <output.js>
"""
import json
import os
import sys

src, out = sys.argv[1], sys.argv[2]
files = {}
for root, dirs, names in os.walk(src):
    dirs.sort()
    for name in sorted(names):
        if name.startswith("."):
            continue
        path = os.path.join(root, name)
        with open(path, encoding="utf-8", errors="replace") as f:
            files["input/" + os.path.relpath(path, src).replace(os.sep, "/")] = f.read()

with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by web/bundle_inputs.py from the input folder.\n")
    f.write("window.BOS_INPUT_FILES = ")
    json.dump(files, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")
print(f"Bundled {len(files)} input files into {out}")
